Update FragPipe Tool to Version 23.0 (#801)
* Updates for FragPipe version 23.0.

* Updates for automated tests.

* Increase profile version to 24.2 and fix version_command.

* Small changes to standardize XML that don't affect behavior. Remove unnecessary str conversion. Indent koina-url parameter. Compare unset groupby parameter to 'None' as is done for other select parameters.

diff --git a/tools/fragpipe/fragpipe b/tools/fragpipe/fragpipe
--- a/tools/fragpipe/fragpipe
+++ b/tools/fragpipe/fragpipe
@@ -22,6 +22,10 @@ while [[ $# -gt 0 ]]; do
             shift
             ionquant_key=$1
             ;;
+        --diatracer_key)
+            shift
+            diatracer_key=$1
+            ;;
         --workflow)
             fragpipe_args+=("$1")
             shift
@@ -35,16 +39,7 @@ while [[ $# -gt 0 ]]; do
     shift
 done
 
-if [[ ! -z "$workflow_file" ]]; then
-    # Because the DIA-NN license is incompatible with bioconda, we remove the feature.
-    grep 'diann.run-dia-nn=true' "$workflow_file" >/dev/null
-    if [[ $? -eq 0 ]]; then
-        echo "Error: DIA-NN is disabled in the FragPipe bioconda package."
-        exit 1
-    fi
-fi
-
-if [[ -z $msfragger_key || -z $ionquant_key ]]; then
+if [[ -z $msfragger_key || -z $ionquant_key || -z $diatracer_key ]]; then
     echo "$license_agreement_text"
     exit 1
 else
@@ -57,6 +52,12 @@ else
     ionquant --key $ionquant_key --help | grep 'License key verified' >/dev/null 2>&1
     if [[ $? -ne 0 ]]; then
         echo "Error: Invalid IonQuant license key"
+        echo "$license_agreement_text"
+        exit 1
+    fi
+    diatracer --key $diatracer_key --help | grep 'License key verified' >/dev/null 2>&1
+    if [[ $? -ne 0 ]]; then
+        echo "Error: Invalid diaTracer license key"
         echo "$license_agreement_text"
         exit 1
     fi
